sudo: false
language: python
python:
- 2.7
- pypy
- 3.4
- 3.5
services:
- rabbitmq
install:
- pip install -r requires/testing.txt -r docs/requirements.txt
script:
- nosetests
- ./setup.py build_sphinx
after_success:
- codecov
deploy:
  provider: pypi
  user: sprockets
  password:
    secure: IJVu1MUk2NtRprWkYL+prPRbWrDdSiP+L06S6xERqYnu+fy1ez8/zODazkQGKagXAAujbJK8OwyCgoMzCGDNHV3/NfFtz9dirGVAD2rXZ6AVfHjtEh31L2b2YzXEK0EnBMRsYRjsqLva6q7tfxzjMWKFria25wsd9bN8VlofNDQ=
  on:
    python: 3.4
    tags: true
    repo: sprockets/sprockets.mixins.amqp
